apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperscale-service-account
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: hyperscale-commerce
automountServiceAccountToken: false
