kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: hyperscale-k8s
nodes:
  # 3 Control-Plane Nodes for HA API & etcd
  - role: control-plane
  - role: control-plane
  - role: control-plane

  # 3 Worker Nodes for distinct scheduling domains & anti-affinity
  - role: worker
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30404
        hostPort: 8404
        protocol: TCP
  - role: worker
  - role: worker
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
